Repository IIvexII/LGU-TimetableAPI, pull requests merged in 2022-11, with the labels that each got.

#26 Issue fixed.
  README.md
Labels: documentation, hacktoberfest-accepted

#34 Fix: Removing '?' as part of filename due invalidity in windows.
  docs/How_to_get_session.md
Labels: bug

#37 [FIX]: fixed the incorrect technologies used in the readme
  README.md
Labels: documentation, hacktoberfest-accepted

#75 feat: Scrap and store all the rooms available in University
  src/controllers/RoomController.js
  src/models/Room.js
  src/models/index.js
  src/populate/Room.js
  src/routes/RoomRouter.js
  src/scrapper/Room.js
  src/scrapper/index.js
Labels: enhancement

#96 feat: fix the issue of returning inaccurate free rooms information
  src/populate/FreeRooms.js
  src/scrapper/RoomSchedule.js
Labels: fix, in-progress

#101 feat: make the time and day parameter optional
  src/controllers/RoomController.js
  src/routes/RoomRouter.js
Labels: fixed, difficulty: moderate
